Lootbox patch
wwosimulation/config pull request #14
Opened 2021-07-27 20:49 UTC by FinnyMarigold58

Fixes wwosimulation/tracker#190

2021-07-27 20:57 UTC, thewilloftheshadow commented
Can you also change the rest of that entire function to use the new db please?

2021-07-27 20:58 UTC, thewilloftheshadow requested changes
.

2021-07-28 03:04 UTC, thewilloftheshadow approved these changes

2021-07-28 03:05 UTC, merged

2021-07-28 07:04 UTC, Gmo666 commented
Uh so do I get my lootboxes back or something