Update shop.js
wwosimulation/config pull request #83
Opened 2022-04-01 20:11 UTC by inno14

2022-04-01 20:26 UTC, Hackante requested changes

2022-04-01 20:26 UTC, Hackante commented on src/shop.js
> +  { id: "auto", name: "Auto Reaction", price: 5, currency: "gems", description: "Get a auto reaction whenever someone pings you!", response: "Ask the staffs to get it at a appropriate place but befor
```suggestion
  { id: "auto", name: "Auto Reaction", price: 5, currency: "gem", description: "Get a auto reaction whenever someone pings you!", response: "Ask the staffs to get it at a appropriate place but before asking keep in mind that Carl bot must be in the server with emoji."}
```

(read line 21)

2022-04-01 20:29 UTC, Hackante reviewed
I will add some chnages too but they don't have anything to do with the new item

2022-04-01 20:58 UTC, Hackante requested changes
what do you mean by place? Do you mean time?

2022-04-01 20:58 UTC, Hackante commented on src/shop.js
> +  { id: "auto", name: "Auto Reaction", price: 5, currency: "gem", description: "Get a auto reaction whenever someone pings you!", response: "Ask the staffs to get it at a appropriate place but before
```suggestion
  { id: "auto", name: "Auto Reaction", price: 5, currency: "gem", description: "Get an auto reaction whenever someone pings you!", response: "Ask a staff member to get it at an appropriate place but before asking keep in mind that Carl bot must be in the server with the emoji."}
```

2022-04-02 09:22 UTC, 3061LRTAGSPKJMORMRT commented
> what do you mean by place? Do you mean time?

@Hackante 

I think they mean channels. It might be weird if they are pinged in announcement channels so "place" probably refers to channel

2022-04-02 16:40 UTC, Hackante requested changes
After that one I can merge it

2022-04-02 16:40 UTC, Hackante commented on src/shop.js
> +  { id: "emoji", name: "Emoji", price: 450, currency: "coin", description: "Gain access to `+write` command. Note the `+emoji` and `+emojilist ` are in progress and will be fixed asap.", role: "66338
```suggestion
  { id: "emoji", name: "Emoji", price: 450, currency: "coin", description: "Gain access to `+write` command. Note: The `+emoji` and `+emojilist` commands are in progress and will be fixed as soon as possible.", role: "663389088354664477" },
```

2022-04-02 16:40 UTC, Hackante commented on src/shop.js
> +  { id: "auto", name: "Auto Reaction", price: 5, currency: "gem", description: "Get an auto reaction whenever someone pings you!", response: "Ask a staff member to get it at an appropriate place but
```suggestion
  { id: "auto", name: "Auto Reaction", price: 5, currency: "gem", description: "Get an auto reaction whenever someone pings you!", response: "Ask a staff member to get it at an appropriate place/channel. But before asking keep in mind that Carl-bot must be in the same server with the emoji."}
```

2022-04-04 17:22 UTC, Hackante requested changes
I wil commit them myself dw

2022-04-04 17:22 UTC, Hackante commented on src/shop.js
> +  { id: "emoji", name: "Emoji", price: 450, currency: "coin", description: "Gain access to `+write` command. Note the `+emoji` and `+emojilist ` are in progress and will be fixed asap.", role: "66338
```suggestion
  { id: "emoji", name: "Emoji", price: 450, currency: "coin", description: "Gain access to `+write` command. Note: The `+emoji` and `+emojilist` commands are in progress and will be fixed as soon as possible.", role: "663389088354664477" },
```

2022-04-04 17:22 UTC, Hackante commented on src/shop.js
> +  { id: "auto", name: "Auto Reaction", price: 5, currency: "gem", description: "Get an auto reaction whenever someone pings you!", response: "Ask a staff member to get it at an appropriate place but
```suggestion
  { id: "auto", name: "Auto Reaction", price: 5, currency: "gem", description: "Get an auto reaction whenever someone pings you!", response: "Ask a staff member to get it at an appropriate place/channel. But before asking keep in mind that Carl-bot must be in the same server with the emoji."}
```

2022-04-04 17:23 UTC, Hackante commented
> I wil commit them myself dw

nvm I can't

2022-04-04 17:23 UTC, inno14 commented
> > I wil commit them myself dw
> 
> nvm I can't

Cuz i already did??

2022-04-04 17:24 UTC, Hackante approved these changes

2022-04-04 17:25 UTC, merged